const userRoles = {
    ADMIN: 'ADMIN',
    SUPER_USER: 'SUPER_USER',
    BASIC_USER: 'BASIC_USER',
    SANITATION_STAFF: 'SANITATION_STAFF',
    DEFECT_STAFF: 'DEFECT_STAFF',
    SAFETY_STAFF: 'SAFETY_STAFF',
    LOSS_STAFF: 'LOSS_STAFF',
    BOOKING_STAFF: 'BOOKING_STAFF',
};

module.exports = {
    userRoles,
}